language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=8-7.2
    - BASE_IMAGE_STABILITY_TAG=2.4.0
  matrix:
    - TAG=8-7.2 SOLR_VER=7.2 SEARCH_API_SOLR_VER=8.x-2.0-alpha3
    - TAG=8-7.1 SOLR_VER=7.1 SEARCH_API_SOLR_VER=8.x-2.0-alpha3
    - TAG=8-7.0 SOLR_VER=7.0 SEARCH_API_SOLR_VER=8.x-2.0-alpha3
    - TAG=8-6.6 SOLR_VER=6.6 SEARCH_API_SOLR_VER=8.x-1.2
    - TAG=8-6.5 SOLR_VER=6.5 SEARCH_API_SOLR_VER=8.x-1.2
    - TAG=8-6.4 SOLR_VER=6.4 SEARCH_API_SOLR_VER=8.x-1.2
    - TAG=8-6.3 SOLR_VER=6.3 SEARCH_API_SOLR_VER=8.x-1.2
    - TAG=8-5.5 SOLR_VER=5.5 SEARCH_API_SOLR_VER=8.x-1.2
    - TAG=7-5.4 SOLR_VER=5.4 SEARCH_API_SOLR_VER=7.x-1.12

script:
  - make && make test

after_success:
  - bash "${TRAVIS_BUILD_DIR}/travis_release"
